# Data Exploration

## Imports

In [1]:
import zstandard as zstd
import pandas as pd

## Sourcing

In [2]:
file_path = "../data/ais_2025_01_01.csv.zst"

In [3]:
df = None

with open(file_path, "rb") as f:
    dctx = zstd.ZstdDecompressor()
    with dctx.stream_reader(f) as reader:
        df = next(pd.read_csv(reader, chunksize=100000))

## Exploration

In [4]:
df.columns

Index(['mmsi', 'base_date_time', 'longitude', 'latitude', 'sog', 'cog',
       'heading', 'vessel_name', 'imo', 'call_sign', 'vessel_type', 'status',
       'length', 'width', 'draft', 'cargo', 'transceiver'],
      dtype='str')

In [5]:
df.dtypes

mmsi                int64
base_date_time        str
longitude         float64
latitude          float64
sog               float64
cog               float64
heading           float64
vessel_name           str
imo                   str
call_sign             str
vessel_type       float64
status            float64
length            float64
width             float64
draft             float64
cargo             float64
transceiver           str
dtype: object

In [6]:
df.head()

,mmsi,base_date_time,longitude,latitude,sog,cog,heading,vessel_name,imo,call_sign,vessel_type,status,length,width,draft,cargo,transceiver
0,671087100,2025-01-01 00:00:00,-66.10297,18.46281,0.0,176.7,NaN,WATER SPIRIT 2,IMO9212424,5VGA7,70.0,0.0,70.0,18.0,4.0,70.0,A
1,367733950,2025-01-01 00:00:00,-122.60927,48.48503,0.0,215.5,115.0,INVICTUS,NaN,WDI7962,37.0,NaN,10.0,3.0,NaN,NaN,B
2,368138010,2025-01-01 00:00:02,-73.84652,40.47715,5.5,286.9,289.0,NEW YORK,IMO9005839,WDL5112,50.0,0.0,58.0,14.0,NaN,50.0,A
3,367637210,2025-01-01 00:00:03,-90.21215,29.12033,0.0,227.6,NaN,MARILYN M,IMO8998148,WDH6367,60.0,0.0,45.0,9.0,NaN,60.0,A
4,368050000,2025-01-01 00:00:03,-72.46934,41.27196,0.0,107.1,340.0,OCULUS,NaN,WDP6852,36.0,NaN,56.0,6.0,NaN,NaN,B

In [7]:
df.count()

mmsi              100000
base_date_time    100000
longitude         100000
latitude          100000
sog                99810
cog                82989
heading            49797
vessel_name        99913
imo                41310
call_sign          88729
vessel_type        99459
status             66586
length             98249
width              97131
draft              56991
cargo              68678
transceiver       100000
dtype: int64

In [8]:
df.describe()

,mmsi,longitude,latitude,sog,cog,heading,vessel_type,status,length,width,draft,cargo
count,1.000000e+05,100000.000000,100000.000000,99810.000000,82989.000000,49797.000000,99459.000000,66586.000000,98249.000000,97131.000000,56991.000000,68678.000000
mean,3.677536e+08,-95.306724,34.503701,2.065994,187.520417,181.811615,47.160428,3.166236,64.558479,12.940513,4.588744,54.912141
std,5.852838e+07,18.873668,7.758435,4.367607,106.483420,104.217846,16.920578,4.529192,81.248274,10.643961,3.052778,17.958592
min,1.036700e+08,-159.358510,15.263630,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.100000,1.000000
25%,3.667479e+08,-117.895820,29.427480,0.000000,95.700000,90.000000,33.000000,0.000000,18.000000,6.000000,2.800000,40.000000
50%,3.674871e+08,-90.638600,30.567160,0.000000,195.400000,181.000000,37.000000,0.000000,27.000000,9.000000,3.200000,53.000000
75%,3.681159e+08,-80.180127,40.643280,0.900000,281.200000,271.000000,57.000000,5.000000,73.000000,16.000000,5.800000,69.000000
max,1.000000e+09,-62.693840,50.110030,42.800000,359.900000,359.000000,190.000000,13.000000,489.000000,60.000000,24.000000,190.000000

In [9]:
df.isna().sum()

mmsi                  0
base_date_time        0
longitude             0
latitude              0
sog                 190
cog               17011
heading           50203
vessel_name          87
imo               58690
call_sign         11271
vessel_type         541
status            33414
length             1751
width              2869
draft             43009
cargo             31322
transceiver           0
dtype: int64